extension DataState {
    public enum USState: String, Modelable, CaseIterable {
        case AL = "area_AL"
        case AK = "area_AK"
        case AZ = "area_AZ"
        case AR = "area_AR"
        case CA = "area_CA"
        case CO = "area_CO"
        case CT = "area_CT"
        case DE = "area_DE"
        case FL = "area_FL"
        case GA = "area_GA"
        case HI = "area_HI"
        case ID = "area_ID"
        case IL = "area_IL"
        case IN = "area_IN"
        case IA = "area_IA"
        case KS = "area_KS"
        case KY = "area_KY"
        case LA = "area_LA"
        case ME = "area_ME"
        case MD = "area_MD"
        case MA = "area_MA"
        case MI = "area_MI"
        case MN = "area_MN"
        case MS = "area_MS"
        case MO = "area_MO"
        case MT = "area_MT"
        case NE = "area_NE"
        case NV = "area_NV"
        case NH = "area_NH"
        case NJ = "area_NJ"
        case NM = "area_NM"
        case NY = "area_NY"
        case NC = "area_NC"
        case ND = "area_ND"
        case OH = "area_OH"
        case OK = "area_OK"
        case OR = "area_OR"
        case PA = "area_PA"
        case RI = "area_RI"
        case SC = "area_SC"
        case SD = "area_SD"
        case TN = "area_TN"
        case TX = "area_TX"
        case UT = "area_UT"
        case VT = "area_VT"
        case VA = "area_VA"
        case WA = "area_WA"
        case WV = "area_WV"
        case WI = "area_WI"
        case WY = "area_WY"
        
        public var abbreviation: String {
            String(rawValue.split(separator: "_").last ?? "Unknown")
        }
    }
}
